# Generated by Django 4.2.4 on 2024-05-13 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0010_alter_ratingcomment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingcomment',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_recieved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ratingcomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_rating', to=settings.AUTH_USER_MODEL),
        ),
    ]
