# Generated by Django 5.0.2 on 2024-04-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_products_image_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image_field',
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
