# Generated by Django 5.0.2 on 2024-04-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_products_image_field_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('card_number', models.CharField(max_length=16)),
                ('card_expiry', models.CharField(max_length=7)),
                ('cardholder_name', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='product_images/'),
        ),
    ]
